package calculadora;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author Guilherme Cicarello Girata GRR20211616
 */
public class calculadora extends javax.swing.JFrame implements ActionListener {
    enum EstadoCalculadora{
        INICIAL,IGNORADO,ENTRADA1,OPERADOR,ENTRADA2,CALCULANDO
    };
    private int num1, num2, result = 0;
    private char sinal;
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonMult;
    private javax.swing.JButton buttonSub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textField;
    // End of variables declaration  
    
    public calculadora() {
        this.setPreferredSize(new Dimension(500, 400));
        initComponents();
        button0.addActionListener(this);
        button1.addActionListener(this);
        button2.addActionListener(this);
        button3.addActionListener(this);
        button4.addActionListener(this);
        button5.addActionListener(this);
        button6.addActionListener(this);
        button7.addActionListener(this);
        button8.addActionListener(this);
        button9.addActionListener(this);
        buttonClear.addActionListener(this);
        buttonEquals.addActionListener(this);
        buttonDiv.addActionListener(this);
        buttonMult.addActionListener(this);
        buttonSub.addActionListener(this);
        buttonAdd.addActionListener(this);
        button0.setActionCommand("0");
        button1.setActionCommand("1");
        button2.setActionCommand("2");
        button3.setActionCommand("3");
        button4.setActionCommand("4");
        button5.setActionCommand("5");
        button6.setActionCommand("6");
        button7.setActionCommand("7");
        button8.setActionCommand("8");
        button9.setActionCommand("9");
        buttonClear.setActionCommand("C");
        buttonEquals.setActionCommand("=");
        buttonDiv.setActionCommand("/");
        buttonMult.setActionCommand("X");
        buttonSub.setActionCommand("-");
        buttonAdd.setActionCommand("+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonSub = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonMult = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(211, 211, 211));

        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        textField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(211, 211, 211));
        jPanel3.setForeground(new java.awt.Color(211, 211, 211));
        jPanel3.setLayout(new java.awt.GridLayout(4, 4));

        button7.setBackground(new java.awt.Color(211, 211, 211));
        button7.setForeground(java.awt.Color.black);
        button7.setText("7");
        jPanel3.add(button7);

        button8.setBackground(new java.awt.Color(211, 211, 211));
        button8.setForeground(java.awt.Color.black);
        button8.setText("8");
        jPanel3.add(button8);

        button9.setBackground(new java.awt.Color(211, 211, 211));
        button9.setForeground(java.awt.Color.black);
        button9.setText("9");
        jPanel3.add(button9);

        buttonAdd.setBackground(new java.awt.Color(211, 211, 211));
        buttonAdd.setForeground(java.awt.Color.black);
        buttonAdd.setText("+");
        jPanel3.add(buttonAdd);

        button4.setBackground(new java.awt.Color(211, 211, 211));
        button4.setForeground(java.awt.Color.black);
        button4.setText("4");
        jPanel3.add(button4);

        button5.setBackground(new java.awt.Color(211, 211, 211));
        button5.setForeground(java.awt.Color.black);
        button5.setText("5");
        jPanel3.add(button5);

        button6.setBackground(new java.awt.Color(211, 211, 211));
        button6.setForeground(java.awt.Color.black);
        button6.setText("6");
        jPanel3.add(button6);

        buttonSub.setBackground(new java.awt.Color(211, 211, 211));
        buttonSub.setForeground(java.awt.Color.black);
        buttonSub.setText("-");
        jPanel3.add(buttonSub);

        button1.setBackground(new java.awt.Color(211, 211, 211));
        button1.setForeground(java.awt.Color.black);
        button1.setText("1");
        jPanel3.add(button1);

        button2.setBackground(new java.awt.Color(211, 211, 211));
        button2.setForeground(java.awt.Color.black);
        button2.setText("2");
        jPanel3.add(button2);

        button3.setBackground(new java.awt.Color(211, 211, 211));
        button3.setForeground(java.awt.Color.black);
        button3.setText("3");
        jPanel3.add(button3);

        buttonMult.setBackground(new java.awt.Color(211, 211, 211));
        buttonMult.setForeground(java.awt.Color.black);
        buttonMult.setText("X");
        jPanel3.add(buttonMult);

        button0.setBackground(new java.awt.Color(211, 211, 211));
        button0.setForeground(java.awt.Color.black);
        button0.setText("0");
        jPanel3.add(button0);

        buttonEquals.setBackground(new java.awt.Color(211, 211, 211));
        buttonEquals.setForeground(java.awt.Color.black);
        buttonEquals.setText("=");
        jPanel3.add(buttonEquals);

        buttonClear.setBackground(new java.awt.Color(211, 211, 211));
        buttonClear.setForeground(java.awt.Color.black);
        buttonClear.setText("C");
        jPanel3.add(buttonClear);

        buttonDiv.setBackground(new java.awt.Color(211, 211, 211));
        buttonDiv.setForeground(java.awt.Color.black);
        buttonDiv.setText("/");
        jPanel3.add(buttonDiv);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calculadora().setVisible(true);
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String comando = e.getActionCommand();
        switch(comando){
            case "0" -> textField.setText(textField.getText()+ "0");
            case "1" -> textField.setText(textField.getText()+ "1");
            case "2" -> textField.setText(textField.getText()+ "2");
            case "3" -> textField.setText(textField.getText()+ "3");
            case "4" -> textField.setText(textField.getText()+ "4");
            case "5" -> textField.setText(textField.getText()+ "5");
            case "6" -> textField.setText(textField.getText()+ "6");
            case "7" -> textField.setText(textField.getText()+ "7");
            case "8" -> textField.setText(textField.getText()+ "8");
            case "9" -> textField.setText(textField.getText()+ "9");
            case "C" -> textField.setText("");
            /** soma **/
            case "+" -> {
                num1 = Integer.parseInt(textField.getText());
                textField.setText(textField.getText()+ "+");
                sinal = '+';
                textField.setText("");
            }
            /** subtração **/
            case "-" -> {
                num1 = Integer.parseInt(textField.getText());
                textField.setText(textField.getText()+ "-");
                sinal = '-';
                textField.setText("");
            }
            /** multiplicação **/
            case "X" -> {
                num1 = Integer.parseInt(textField.getText());
                sinal = 'X';
                textField.setText("");
            }
            /** divisão **/
            case "/" -> {
                num1 = Integer.parseInt(textField.getText());
                sinal = '/';
                textField.setText("");
            }
            /** igual **/
            case "=" -> {
                num2 = Integer.parseInt(textField.getText());
                /** operações **/
                switch(sinal){
                    case '+' -> result = num1+num2;
                    case '-' -> result = num1-num2;
                    case 'X' -> result = num1*num2;
                    case '/' -> {
                        try {
                            result = num1/num2;
                          } catch (Exception ex) {
                            result =0;
                          }
                    }
                    default -> {
                }
                }
                textField.setText(String.valueOf(result));
                num1 = result;
            }
            default -> {
            }
        }
    }
}